- basepath: spinnsyn-backend
  serviceurlProperty: spinnsyn.backend.url
  paths:
    get:
      - /api/v1/veileder/vedtak

- basepath: spinnsyn-backend-testdata
  devOnly: true
  serviceurlProperty: spinnsyn.backend.url
  paths:
    post:
      - /api/v1/mock/vedtak/{fnr}
      - /api/v1/mock/annullering/{fnr}
      - /api/v2/testdata/vedtak/{fnr}
    delete:
      - /api/v1/mock/vedtak/{fnr}

