- basepath: spinnsyn-backend
  serviceurlProperty: spinnsyn.backend.url
  paths:
    get:
      - /api/v3/veileder/vedtak

- basepath: spinnsyn-backend-testdata
  devOnly: true
  serviceurlProperty: spinnsyn.backend.url
  paths:
    get:
      - /api/v1/testdata/fnr
    post:
      - /api/v1/testdata/vedtak
      - /api/v1/testdata/annullering
    delete:
      - /api/v1/testdata/vedtak

